title: "Terrell Family Reunion"
description: "Annual family reunion hub"
theme: null

collections:
  years:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: years
    values:
      layout: default
